version: 2

jobs:
  test-build-deploy:
    working_directory: ~/app
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v12-{{ checksum "yarn.lock" }}
            - yarn-packages-v12-

      - run:
          name: Install Dependencies
          command: |
            yarn install
            yarn autoclean --force

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/Cypress
            - node_modules

      - run:
          name: Run linters
          command: yarn run lint

      - run:
          name: Start background app
          command:
            'if [[ -f ./cypress/integration/homework.spec.js ]]; then if [[ -s
            ./cypress/integration/homework.spec.js ]]; then yarn start:run;
            fi;fi'
          background: true

      - run:
          name: Cypress tests
          command:
            'if [[ -f ./cypress/integration/homework.spec.js ]]; then if [[ -s
            ./cypress/integration/homework.spec.js ]]; then yarn run
            cypress:run; fi;fi'

      - run:
          name: Build app
          command: yarn build

      - run:
          name: Set PR number
          command: |
            echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
            source $BASH_ENV
            echo $CIRCLE_PR_NUMBER

      - run:
          name: Remove old build
          command:
            ssh -o StrictHostKeyChecking=no root@51.15.83.43 rm -rf
            /var/www/sep-pr-$CIRCLE_PR_NUMBER

      - run:
          name: Copy new build
          command:
            scp -v -o StrictHostKeyChecking=no -r build
            root@51.15.83.43:/var/www/sep-pr-$CIRCLE_PR_NUMBER

      - run:
          name: Create dns zone
          command:
            ssh -o StrictHostKeyChecking=no root@51.15.83.43
            "/var/www/setup-server/index.js --address sep-pr-$CIRCLE_PR_NUMBER"
