version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/base:8
      environment:
        TERM: xterm

jobs:
  cache-warm:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - yarn-packages-v7-{{ checksum "yarn.lock" }}
            - yarn-packages-v7-

      - run: &install_deps
          name: Install Dependencies
          command: yarn install

      - save_cache: &save_cache
          name: Save Yarn Package Cache
          key: yarn-packages-v7-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache

      - run:
          name: Run linters
          command: yarn run lint

  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache

      - run:
          name: Unit tests
          command: yarn test

  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache

      - run:
          name: Start background app
          command: yarn start
          background: true

      - run:
          name: Cypress tests
          command: yarn run cypress:run

  build-and-deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache

      - run:
          name: Build app
          command: yarn build

      - run:
          name: Set PR number
          command: |
            echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
            source $BASH_ENV
            echo $CIRCLE_PR_NUMBER

      - run:
          name: Remove service workers
          command: rm ~/app/build/service-worker.js

      - run:
          name: Remove old build
          command:
            ssh -o StrictHostKeyChecking=no root@51.15.83.43 rm -rf
            /var/www/sep-pr-$CIRCLE_PR_NUMBER

      - run:
          name: Copy new build
          command:
            scp -v -o StrictHostKeyChecking=no -r ~/app/build
            root@51.15.83.43:/var/www/sep-pr-$CIRCLE_PR_NUMBER

      - run:
          name: Create dns zone
          command:
            ssh -o StrictHostKeyChecking=no root@51.15.83.43
            "/var/www/setup-server/index.js --address sep-pr-$CIRCLE_PR_NUMBER"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - cache-warm

      - lint:
          requires:
            - cache-warm

      - unit-tests:
          requires:
            - cache-warm

      - integration-tests:
          requires:
            - cache-warm

      - build-and-deploy:
          requires:
            - lint
            - unit-tests
            - integration-tests
